#! /bin/sh

start() {
  pkill -x "$1"
  {
    sleep 0.2
    "$@" &
  }
}

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

xmodmap "$HOME/.Xmodmap" &

#bspc monitor -d I II III IV V VI VII VIII IX X
monitor="$(xrandr | grep " connected" | grep "HDMI-A-0")"

if [ "$monitor" = "" ]; then
  bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 0
  xrandr --output HDMI-A-0 --off
else
  xrandr --output HDMI-A-0 --mode 1920x1080 --pos 1920x0
  bspc monitor eDP -d 1 2 3 4 5
  bspc monitor HDMI-A-0 -d 6 7 8 9 0
fi

config window_gap 10

# bspc config normal_border_color "#323D43"
# bspc config active_border_color "#a7c080"
config normal_border_color {{ bg0 }}
config active_border_color {{ bg0 }}
config focused_border_color {{ bg0 }}

config split_ratio 0.52
config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer true

bspc rule -r *

floating="Arandr Lxappearance Pavucontrol NMTUI"

for c in $floating; do
  rule "$c" state=floating
done

pgrep -x sxhkd >/dev/null || sxhkd &
# sxhkd &
start /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# usr/bin/dunst &
start "$HOME"/.config/polybar/launch.sh bspwm
start mopidy
start nitrogen --restore
start picom --config "$HOME"/.config/bspwm/picom.conf --experimental-backends
start xsetroot -cursor_name left_ptr
start ~/.local/bin/brdr
start nm-applet
start mpDris2

# eww kill
# eww daemon && eww open bar &
# [ ! -s ~/.config/mpd/pid ] && mpd &&
