#! /bin/sh

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X


bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -r *

bspc rule -a firefox desktop='^2' follow=on -o
bspc rule -a Arandr state=floating

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
xmodmap $HOME/.Xmodmap
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
usr/bin/dunst &
$HOME/.config/polybar/launch.sh
nitrogen --restore
picom --config $HOME/.config/picom/picom.conf --experimental-backends
xinput set-prop "MSFT0001:00 06CB:CE2D Touchpad" "libinput Natural Scrolling Enabled" 1
