#!/bin/sh

start() {
  pkill -x "$1"
  {
    sleep 0.2
    "$@" &
  }
}

monitor="$(xrandr | grep " connected" | grep "HDMI-A-0")"

if [ "$monitor" = "" ]; then
  bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 0
  xrandr --output HDMI-A-0 --off
else
  xrandr --output HDMI-A-0 --mode 1920x1080 --pos 1920x0
  bspc monitor eDP -d 1 2 3 4 5
  bspc monitor HDMI-A-0 -d 6 7 8 9 0
fi

start picom --config ~/.config/awesome/picom.conf --experimental-backends
start xmodmap ~/.Xmodmap
start /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
start mopidy
start nitrogen --restore
start nm-applet
start mpDris2
