[helpers]

[default]
depends = []

[default.files]
bspwmrc = "~/.config/bspwm/bspwmrc"
dunstrc = "~/.config/dunst/dunstrc"
"kitty.conf" = "~/.config/kitty/kitty.conf"
polybar = "~/.config/polybar"
sxhkdrc = "~/.config/sxhkd/sxhkdrc"
zshrc = "~/.zshrc"
nvim = "~/.config/nvim"
picom = "~/.config/picom"
chrome = "~/.mozilla/firefox/307rfa7n.default-release/chrome"
"starship/starship.toml" = "~/.config/starship.toml"
"starship/config-transient.toml" = "~/.config/starship/config-transient.toml"
eww = "~/.config/eww"
rofi = "~/.config/rofi/config.rasi"
bin = "~/.local/bin"

[default.variables]
