[helpers]

[default]
depends = []

[default.files]
# nvim = "~/.config/nvim"
bin = "~/.local/bin"
xmodmap = "~/.Xmodmap"

# [default.variables]

[mpd.files]
mpd = "~/.config/mpd/mpd.conf"
mpDris2 = "~/.config/mpd/mpDris2.conf"
ncmpcpp = {target="~/.config/ncmpcpp", type="symbolic"}

[awesome.files]
awesome = {target="~/.config/awesome", type = "symbolic"}

[openbox]
depends = ["polybar", "rofi", "dunst"]

[openbox.files]
openbox = "~/.config/openbox"

[bspwm]
depends = ["polybar","rofi","dunst"]

[bspwm.files]
bspwmrc = "~/.config/bspwm/bspwmrc"
sxhkdrc = "~/.config/sxhkd/sxhkdrc"
picom = "~/.config/picom"

[polybar.files]
polybar = {target = "~/.config/polybar", type = "symbolic"}

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"
"starship/config-transient.toml" = "~/.config/starship/config-transient.toml"

[zsh.files]
zshrc = "~/.zshrc"

[kitty.files]
kitty = "~/.config/kitty/kitty.conf"

[rofi.files]
rofi = "~/.config/rofi/config.rasi"

[eww.files]
eww = "~/.config/eww"

[firefox.files]
chrome = "~/.mozilla/firefox/wlmgcclo.default-release/chrome"

[nvchad.files]
customchad = "~/.config/nvim/lua/custom"

[dunst.files]
dunstrc = "~/.config/dunst/dunstrc"
