[helpers]

[default]
depends = []

[default.files]
bspwmrc = "~/.config/bspwm/bspwmrc"
dunstrc = "~/.config/dunst/dunstrc"
"kitty.conf" = "~/.config/kitty/kitty.conf"
polybar = "~/.config/polybar"
sxhkdrc = "~/.config/sxhkd/sxhkdrc"

[default.variables]
