[helpers]

[colors.variables]
# schemename = "Everforest"
# bg0 = "#2b3339"
# bg1 = "#323c41"
# bg2 = "#3a454a"
# bg3 = "#445055"
# bg4 = "#4c555b"
# bg5 = "#53605c"
# fg = "#d3c6aa"
# red = "#e67e80"
# orange = "#e69875"
# yellow = "#dbbc7f"
# green = "#a7c080"
# aqua = "#83c092"
# blue = "#7fbbb3"
# purple = "#d699b6"
# grey0 = "#7a8478"
# grey1 = "#859289"
# grey2 = "#9da9a0"
# accent = "#a7c080"
schemename = "Catppuccin"
bg0 = "#11111b"
bg1 = "#181825"
bg2 = "#1e1e2e"
bg3 = "#313244"
bg4 = "#45475a"
bg5 = "#585b70"
fg = "#cdd6f4"
fg1 = "#bac2de"
red = "#f38ba8"
pink = "#f5c2e7"
orange = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
aqua = "#89DCEB"
blue = "#89b4fa"
purple = "#cba6f7"
rosewater = "#f5e0dc"
lavender = "#b4befe"
maroon = "#EBA0AC"
grey0 = "#6c7086"
grey1 = "#7f849c"
grey2 = "#9399b2"
accent = "#cba6f7"

[default]
depends = []
files = { "bin" = "~/.local/bin", "xmodmap" = "~/.Xmodmap", "xresources" = "~/.config/X11/xresources", "cfg/gitconfig" = "~/.config/git/config" }

[awesome]
files = { "cfg/awesome" = { target="~/.config/awesome", type = "symbolic" } }

[bspwm]
depends = ["polybar", "rofi", "dunst", "colors"]
files = {"cfg/bspwmrc" = "~/.config/bspwm/bspwmrc", "cfg/sxhkdrc" = "~/.config/sxhkd/sxhkdrc", "cfg/picom/picom.conf" = "~/.config/bspwm/picom.conf"}

[dunst]
files = { "cfg/dunstrc" = "~/.config/dunst/dunstrc" }

[eww]
files = { "cfg/eww" = "~/.config/eww" }

[firefox]
depends = ["colors"]
files = { "mozchrome" = "~/.mozilla/firefox/9om0wumt.default-release/chrome" }

[fonts]
files = { "fonts" = {target = "~/.fonts", type = "symbolic"} }

[kitty]
depends = ["colors"]
files = { "cfg/kitty/config" = "~/.config/kitty/kitty.conf", "cfg/kitty/diff" = "~/.config/kitty/diff.conf", "cfg/kitty/dotedit" = "~/.config/kitty/dotedit.session", "cfg/kitty/scratchpad" = "~/.config/kitty/scratchpad.session" }

[music]
files = { "cfg/mpd" = "~/.config/mpd", "cfg/mopidy" = "~/.config/mopidy", "cfg/ncmpcpp" = {target = "~/.config/ncmpcpp/config", type = "symbolic"} }

[neofetch]
files = { "cfg/neofetch" = "~/.config/neofetch/config.conf" }

[nvchad]
files = { "cfg/customchad" = "~/.config/nvim/lua/custom" }

[openbox]
depends = ["polybar", "rofi", "dunst", "colors"]
files = { "cfg/openbox" = "~/.config/openbox", "themes/openbox-3" = "~/.themes/openbox/openbox-3" }

[polybar]
depends = ["colors"]
files = { "cfg/polybar" = "~/.config/polybar" }

[ranger]
files = { "cfg/ranger" = "~/.config/ranger" }

[rofi]
depends = ["colors"]
files = { "cfg/rofi" = "~/.config/rofi" }

[i3]
depends = ["polybar", "rofi", "dunst", "colors"]
files = { "cfg/i3" = "~/.config/i3" }

[starship]
depends = ["colors"]
files = { "cfg/starship/starship.toml" = "~/.config/starship.toml"}

[zsh]
depends = ["colors"]
files = { zshrc = "~/.zshrc" }
