[helpers]

[default]
depends = []

[default.files]
# nvim = "~/.config/nvim"
bin = "~/.local/bin"
xmodmap = "~/.Xmodmap"

# [default.variables]

[mpd.files]
mpd = "~/.config/mpd/mpd.conf"
mpDris2 = "~/.config/mpd/mpDris2.conf"
ncmpcpp = {target="~/.config/ncmpcpp", type="symbolic"}

[awesome.files]
"cfg/awesome" = {target="~/.config/awesome", type = "symbolic"}

[openbox]
depends = ["polybar", "rofi", "dunst"]

[openbox.files]
"cfg/openbox" = "~/.config/openbox"

[bspwm]
depends = ["polybar","rofi","dunst"]

[bspwm.files]
"cfg/bspwmrc" = "~/.config/bspwm/bspwmrc"
"cfg/sxhkdrc" = "~/.config/sxhkd/sxhkdrc"
"cfg/picom" = "~/.config/picom"

[polybar.files]
"cfg/polybar" = {target = "~/.config/polybar", type = "symbolic"}

[starship.files]
"cfg/starship/starship.toml" = "~/.config/starship.toml"
"cfg/starship/config-transient.toml" = "~/.config/starship/config-transient.toml"

[zsh.files]
zshrc = "~/.zshrc"

[kitty.files]
"cfg/kitty" = "~/.config/kitty/kitty.conf"

[rofi.files]
"cfg/rofi" = "~/.config/rofi/config.rasi"

[eww.files]
"cfg/eww" = "~/.config/eww"

[firefox.files]
chrome = "~/.mozilla/firefox/wlmgcclo.default-release/chrome"

[nvchad.files]
"cfg/customchad" = "~/.config/nvim/lua/custom"

[dunst.files]
"cfg/dunstrc" = "~/.config/dunst/dunstrc"
