[helpers]

[default]
depends = []

[default.files]
# nvim = "~/.config/nvim"
bin = "~/.local/bin"
xmodmap = "~/.Xmodmap"

# [default.variables]

[openbox]
depends = ["polybar"]

[openbox.files]
openbox = "~/.config/openbox"

[bspwm]
depends = ["polybar"]

[bspwm.files]
bspwmrc = "~/.config/bspwm/bspwmrc"
dunstrc = "~/.config/dunst/dunstrc"
sxhkdrc = "~/.config/sxhkd/sxhkdrc"
picom = "~/.config/picom"

[polybar.files]
polybar = {target = "~/.config/polybar", type = "symbolic"}

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"
"starship/config-transient.toml" = "~/.config/starship/config-transient.toml"

[zsh.files]
zshrc = "~/.zshrc"

[kitty.files]
kitty = "~/.config/kitty/kitty.conf"

[rofi.files]
rofi = "~/.config/rofi/config.rasi"

[eww.files]
eww = "~/.config/eww"

[firefox.files]
chrome = "~/.mozilla/firefox/1rigvdzk.default-release/chrome"

[nvchad.files]
customchad = "~/.config/nvim/lua/custom"
