[helpers]

[colors.variables]
schemename = "Catppuccin"
bg0 = "#000000"
bg1 = "#000a0e"
bg2 = "#061115"
bg3 = "#0d181c"
bg4 = "#131e22"
bg5 = "#1c272b"
fg = "#e5e5e5"
fg1 = "#D9D7D6"
red = "#DF5B61"
pink = "#F16269"
orange = "#E89982"
yellow = "#ecd28b"
green = "#78B892"
teal = "#7ACFE4"
aqua = "#67AFC1"
blue = "#6791C9"
purple = "#BC83E3"
rosewater = "#f6dc95"
lavender = "#b4befe"
maroon = "#C488EC"
grey0 = "#242f33"
grey1 = "#313c40"
grey2 = "#3b464a"
accent = "#6791C9"

[default]
depends = []
files = { "bin" = "~/.local/bin", "xmodmap" = "~/.Xmodmap", "xresources" = "~/.config/X11/xresources", "cfg/gitconfig" = "~/.config/git/config" }

[awesome]
files = { "cfg/awesome" = { target="~/.config/awesome", type = "symbolic" } }

[bspwm]
depends = ["polybar", "rofi", "dunst", "colors"]
files = {"cfg/bspwmrc" = "~/.config/bspwm/bspwmrc", "cfg/sxhkdrc" = "~/.config/sxhkd/sxhkdrc", "cfg/picom/picom.conf" = "~/.config/bspwm/picom.conf"}

[dunst]
files = { "cfg/dunstrc" = "~/.config/dunst/dunstrc" }

[eww]
files = { "cfg/eww" = "~/.config/eww" }

[firefox]
depends = ["colors"]
files = { "mozchrome" = "~/.mozilla/firefox/aqops9ab.default-release/chrome" }

[fonts]
files = { "fonts" = {target = "~/.fonts", type = "symbolic"} }

[kitty]
depends = ["colors"]
files = { "cfg/kitty/config" = "~/.config/kitty/kitty.conf", "cfg/kitty/diff" = "~/.config/kitty/diff.conf", "cfg/kitty/dotedit" = "~/.config/kitty/dotedit.session", "cfg/kitty/scratchpad" = "~/.config/kitty/scratchpad.session" }

[music]
files = { "cfg/mpd" = "~/.config/mpd", "cfg/mopidy" = "~/.config/mopidy", "cfg/ncmpcpp" = {target = "~/.config/ncmpcpp/config", type = "symbolic"} }

[neofetch]
files = { "cfg/neofetch" = "~/.config/neofetch/config.conf" }

[nvchad]
files = { "cfg/customchad" = "~/.config/nvim/lua/custom" }

[openbox]
depends = ["polybar", "rofi", "dunst", "colors"]
files = { "cfg/openbox" = "~/.config/openbox", "themes/openbox-3" = "~/.themes/openbox/openbox-3" }

[polybar]
depends = ["colors", "dunst"]
files = { "cfg/polybar" = "~/.config/polybar" }

[ranger]
files = { "cfg/ranger" = "~/.config/ranger" }

[redshift]
files = { "cfg/redshift" = "~/.config/redshift" }

[rofi]
depends = ["colors"]
files = { "cfg/rofi" = "~/.config/rofi" }

[i3]
depends = ["polybar", "rofi", "dunst", "colors"]
files = { "cfg/i3" = "~/.config/i3" }

[starship]
depends = ["colors"]
files = { "cfg/starship/starship.toml" = "~/.config/starship.toml"}

[zsh]
depends = ["colors"]
files = { zshrc = "~/.zshrc" }
