#!/bin/sh
if [ "$1" = "stop" ]; then
  stop=true
else
  stop=false
fi

start() {

  if [ "$1" = "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1" ]; then
    pkill polkit-gnome
  fi

  pkill -x "$1"

  {
    sleep 0.2
    if [ $stop = false ]; then
      "$@" &
    fi
  }

}

# monitor="$(xrandr | grep " connected" | grep "HDMI-A-0")"
#
# if [ "$monitor" = "" ]; then
#   xrandr --output HDMI-A-0 --off
# else
#   xrandr --output HDMI-A-0 --mode 1920x1080 --pos 1920x0
# fi
start picom --config ~/.config/dk/picom.conf --experimental-backends
start xmodmap ~/.Xmodmap
start xrdb merge ~/.config/X11/xresources
start lxsession
start mopidy
start nitrogen --restore
start nm-applet
start mpDris2
start start-pulseaudio-x11 &
start earlyoom -m 5 -N /home/syahdan/.local/bin/oomn --avoid '(^|/)(init|systemd|Xorg|sshd|awesome|sddm|sddm-helper)$' &
start xidlehook --not-when-audio --not-when-fullscreen --timer 120 "xrandr --output eDP --brightness .1" "xrandr --output eDP --brightness 1" --timer 10 "i3lock --date-color '#cdd6f4' --time-color '#cdd6f4' --blur 5 --clock --indicator --time-str='%H:%M:%S' --date-str='%A, %Y-%m-%d'" "xrandr --output eDP --brightness 1" --timer 7200 "systemctl poweroff" ""
start xcape -e "#66=Escape;#133=Super_R|d"
start ~/.config/polybar/launch.sh openbox
